-- Demo data (fictional). Password is NOT stored here; see demo-password.txt
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (1,'alpha.founder@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','founder','Alpha Founder','India','Bengaluru','Building AI triage for rural clinics','Second-time founder. Alpha Startup helps primary-health clinics in underserved regions prioritise patients with an offline-first triage assistant. Previously led product at a digital-health scale-up.','https://www.linkedin.com/',1,3,6,'HealthTech,AI / ML','Seed','Alpha Startup',1500000,'12 clinics live · 40k patient visits · 18% MoM growth',NULL,NULL,NULL,NULL,'',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 5184000000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 0));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (2,'bravo.founder@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','founder','Bravo Founder','Germany','Berlin','Making city power grids smarter, one sensor at a time','Electrical engineer turned founder. Bravo Startup builds low-cost IoT sensors that help municipal utilities detect transformer failures before blackouts happen.','https://www.linkedin.com/',1,2,6,'Climate / CleanTech,Hardware / IoT','Pre-seed','Bravo Startup',600000,'3 pilot cities · 2 LOIs from regional utilities',NULL,NULL,NULL,NULL,'',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 4924800000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 7200000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (3,'charlie.founder@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','founder','Charlie Founder','Ghana','Accra','Cross-border payments for African SMEs','Ex-bank product manager building Charlie Startup: instant, low-fee settlement between African markets for small exporters.','https://www.linkedin.com/',1,2,6,'Fintech','Seed','Charlie Startup',2000000,'$1.2M monthly volume · 600 SMEs onboarded',NULL,NULL,NULL,NULL,'',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 4665600000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 14400000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (4,'delta.founder@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','founder','Delta Founder','Mexico','Mexico City','Interactive classrooms for Spanish-speaking teachers','Former teacher creating Delta Startup, a lesson-building tool that turns curriculum goals into interactive classroom activities.','https://www.linkedin.com/',1,1,6,'EdTech,Consumer','Pre-seed','Delta Startup',300000,'1,800 teachers on the waitlist · prototype in 14 schools',NULL,NULL,NULL,NULL,'',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 4406400000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 21600000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (5,'alpha.investor@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','investor','Alpha Investor','India','Mumbai','Partner at Alpha Demo Fund · backing health & fintech founders','We write first cheques into founders solving large, under-served problems across South Asia and Africa. 40+ companies, 6 exits.','https://www.linkedin.com/',1,3,6,'HealthTech,Fintech,AI / ML','Pre-seed,Seed',NULL,NULL,NULL,'Venture Capitalist',250000,1500000,'40+ companies including 3 unicorn-track health platforms.','',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 4147200000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 28800000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (6,'bravo.investor@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','investor','Bravo Investor','United Kingdom','London','Angel investor · ex-SaaS operator','Operator-turned-angel. I back technical founders early and like to help with go-to-market and first enterprise sales.','https://www.linkedin.com/',1,2,6,'SaaS,Fintech,AI / ML','Pre-seed,Seed',NULL,NULL,NULL,'Angel Investor',25000,150000,'22 angel investments, 4 follow-on rounds.','',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 3888000000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 36000000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (7,'charlie.investor@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','investor','Charlie Investor','Singapore','Singapore','Principal at Bravo Demo Ventures · deep tech & climate','Meridian invests in hardware-enabled and deep-tech companies across Asia-Pacific and Europe.','https://www.linkedin.com/',1,2,6,'Climate / CleanTech,DeepTech,Hardware / IoT','Seed,Series A',NULL,NULL,NULL,'Venture Capitalist',500000,3000000,'Portfolio spans grid tech, battery materials and industrial robotics.','',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 3628800000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 43200000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (8,'delta.investor@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','investor','Delta Investor','Nigeria','Lagos','Lead, Charlie Demo Angels · fintech, agri & education','Leading a 60-member angel syndicate backing African founders at the earliest stages.','https://www.linkedin.com/',1,1,6,'Fintech,AgriTech,EdTech','Pre-seed,Seed',NULL,NULL,NULL,'Angel Group',50000,400000,'31 syndicate deals since 2021.','',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 3369600000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 50400000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (9,'alpha.mentor@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','mentor','Alpha Mentor','India','Hyderabad','Two-time founder & former CTO · product, tech & fundraising','I help technical founders go from prototype to product-market fit, and prepare for their first institutional round.','https://www.linkedin.com/',1,3,6,'AI / ML,SaaS,HealthTech','Idea,Pre-seed,Seed',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tech,Product,Fundraising',15,((CAST(strftime('%s','now') AS INTEGER)*1000) - 3110400000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 57600000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (10,'bravo.mentor@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','mentor','Bravo Mentor','Netherlands','Amsterdam','Growth operator · marketing, sales & positioning','Built go-to-market engines at three European scale-ups. I coach founders on positioning, pricing and their first 100 customers.','https://www.linkedin.com/',1,2,6,'Consumer,E-commerce,SaaS','Pre-seed,Seed,Series A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Marketing,Sales,Strategy',12,((CAST(strftime('%s','now') AS INTEGER)*1000) - 2851200000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 64800000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (11,'charlie.mentor@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','mentor','Charlie Mentor','United States','New York','Fintech CFO & fundraising coach','Former CFO of two fintech companies and advisor to 30+ early-stage startups on financial models, cap tables and investor readiness.','https://www.linkedin.com/',1,3,6,'Fintech,Web3','Seed,Series A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Finance,Fundraising,Legal',18,((CAST(strftime('%s','now') AS INTEGER)*1000) - 2592000000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 72000000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (12,'delta.mentor@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','mentor','Delta Mentor','South Africa','Cape Town','Operations & talent for scaling teams','I help founders build the operating rhythm, hiring plans and culture needed to grow from 5 to 50 people.','https://www.linkedin.com/',1,1,6,'AgriTech,Climate / CleanTech,Fintech','Seed,Series A,Series B+',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Operations,Talent / HR,Strategy',10,((CAST(strftime('%s','now') AS INTEGER)*1000) - 2332800000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 79200000));
INSERT INTO users (id,email,password_hash,role,name,country,city,headline,bio,linkedin_url,email_verified,trust_level,onboarding_step,industries,stages,startup_name,funding_goal,traction,investor_type,ticket_min,ticket_max,portfolio,expertise,years_exp,created_at,last_seen) VALUES (13,'echo.founder@inverge.test','pbkdf2$15000$deFNzBKU7iQvQ9Uq30FqWA$4LPCAqFskyNurdvASTzW-UMS1LUSoWC6rq_Gpwcgm9E','founder','Echo Founder','Portugal','Lisbon','Exploring ideas in logistics tech','Just joined INverge — verification pending.','https://www.linkedin.com/',1,0,6,'Mobility','Idea','Untitled project',100000,NULL,NULL,NULL,NULL,NULL,'',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 2073600000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 86400000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile1',1,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (1,'gov_id','seedfile1','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile2',1,'doc','registration.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (1,'registration','seedfile2','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile3',1,'doc','pitch_deck.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (1,'pitch_deck','seedfile3','pending',1,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile4',2,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (2,'gov_id','seedfile4','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile5',2,'doc','registration.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (2,'registration','seedfile5','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile6',2,'doc','pitch_deck.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (2,'pitch_deck','seedfile6','pending',1,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile7',3,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (3,'gov_id','seedfile7','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile8',3,'doc','registration.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (3,'registration','seedfile8','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile9',3,'doc','pitch_deck.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (3,'pitch_deck','seedfile9','pending',1,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile10',4,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (4,'gov_id','seedfile10','pending',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile11',4,'doc','pitch_deck.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (4,'pitch_deck','seedfile11','pending',1,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile12',5,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (5,'gov_id','seedfile12','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile13',5,'doc','investment_proof.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (5,'investment_proof','seedfile13','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile14',6,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (6,'gov_id','seedfile14','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile15',6,'doc','investment_proof.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (6,'investment_proof','seedfile15','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile16',7,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (7,'gov_id','seedfile16','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile17',7,'doc','investment_proof.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (7,'investment_proof','seedfile17','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile18',8,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (8,'gov_id','seedfile18','pending',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile19',9,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (9,'gov_id','seedfile19','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile20',9,'doc','resume.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (9,'resume','seedfile20','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile21',10,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (10,'gov_id','seedfile21','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile22',10,'doc','resume.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (10,'resume','seedfile22','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile23',11,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (11,'gov_id','seedfile23','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile24',11,'doc','resume.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (11,'resume','seedfile24','approved',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO files (id,owner_id,kind,name,mime,size,data,created_at) VALUES ('seedfile25',12,'doc','gov_id.pdf','application/pdf',411,'JVBERi0xLjQKMSAwIG9iajw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAyIDAgUj4+ZW5kb2JqCjIgMCBvYmo8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PmVuZG9iagozIDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9NZWRpYUJveFswIDAgMzAwIDEyMF0vQ29udGVudHMgNCAwIFIvUmVzb3VyY2VzPDwvRm9udDw8L0YxIDUgMCBSPj4+Pj4+ZW5kb2JqCjQgMCBvYmo8PC9MZW5ndGggNjY+PnN0cmVhbQpCVCAvRjEgMTQgVGYgMjAgNjAgVGQgKElOdmVyZ2UgZGVtbyBkb2N1bWVudCAtIHBsYWNlaG9sZGVyKSBUaiBFVAplbmRzdHJlYW0gZW5kb2JqCjUgMCBvYmo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UeXBlMS9CYXNlRm9udC9IZWx2ZXRpY2E+PmVuZG9iagp0cmFpbGVyPDwvUm9vdCAxIDAgUj4+CiUlRU9G',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1800000000));
INSERT INTO documents (user_id,kind,file_id,status,is_public,created_at) VALUES (12,'gov_id','seedfile25','pending',0,((CAST(strftime('%s','now') AS INTEGER)*1000) - 1728000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (1,5,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1080000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (1,10,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1044000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (1,11,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1008000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (1,9,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 972000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (5,3,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 936000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (5,9,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 900000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (5,6,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 864000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (9,2,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 828000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (9,11,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 792000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (11,3,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 756000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (11,6,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 720000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (11,5,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 684000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (2,7,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 648000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (2,10,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 612000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (3,8,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 576000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (12,3,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 540000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (12,8,'accepted',((CAST(strftime('%s','now') AS INTEGER)*1000) - 504000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (4,9,'pending',((CAST(strftime('%s','now') AS INTEGER)*1000) - 468000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (8,3,'pending',((CAST(strftime('%s','now') AS INTEGER)*1000) - 432000000));
INSERT INTO connections (requester_id,addressee_id,status,created_at) VALUES (7,1,'pending',((CAST(strftime('%s','now') AS INTEGER)*1000) - 396000000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (1,1,'funding','Alpha Startup is opening a $1.5M seed round. 12 clinics live, 40k patient visits, and an 18% MoM growth rate. Looking for health-focused investors who understand last-mile care. Our deck is on my profile for verified investors.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 10800000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (1,6);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (1,7);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (1,8);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (1,10);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (1,11);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (1,12);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (1,2);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (1,3);
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (1,5,'Impressive traction on clinic activation. Would love to see your retention data — sending a message.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 9000000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (1,10,'Happy to help with your seed narrative. The offline-first angle is your strongest story.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 7920000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (1,9,'Strong team and a clear wedge. Happy to help with your technical diligence story.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 6840000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (2,5,'call','Alpha Demo Fund is actively looking for pre-seed and seed founders in HealthTech and Fintech across South Asia and Africa. Cheque size $250K–$1.5M. Share a short pitch with traction numbers and we will respond within a week.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 25200000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (2,1);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (2,3);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (2,4);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (2,2);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (2,12);
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (2,3,'Is cross-border payments infrastructure in scope?',((CAST(strftime('%s','now') AS INTEGER)*1000) - 23400000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (2,5,'Absolutely — especially if you have real volume. Send a pitch via Alignment.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 22320000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (2,1,'Thanks Alpha Investor — sending a pitch your way shortly.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 21240000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (3,10,'insight','Three questions I ask every founder before their first fundraise: 1) What do you know about your customers that investors do not? 2) What milestone will this round fund? 3) What happens if you raise half? Clear answers beat polished slides.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 39600000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (3,1);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (3,2);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (3,3);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (3,4);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (3,5);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (3,6);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (3,7);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (3,12);
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (3,2,'Number 3 is a great forcing function. Working on it now.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 37800000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (3,1,'Great list. Saving this for our seed prep.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 36720000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (4,2,'update','Bravo Startup just finished pilot #3: our sensors flagged a failing transformer 11 days before it would have caused an outage. We are now in talks with two regional utilities. Huge thanks to everyone who introduced us.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 72000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (4,7);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (4,10);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (4,11);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (4,1);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (4,12);
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (4,7,'That is a strong proof point. Let us talk — Meridian is looking at grid tech.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 70200000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (5,3,'funding','Charlie Startup is raising a $2M seed to expand settlement corridors from West Africa to East Africa. We process $1.2M a month for 600 SMEs. Looking for fintech investors with African market experience.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 93600000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (5,6);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (5,8);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (5,11);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (5,12);
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (5,5,'Charlie Startup looks interesting — let us talk about corridors and unit economics.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 91800000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (5,11,'Happy to review your FX and settlement cost model before you raise.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 90720000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (6,11,'insight','Cap table hygiene tip: model your next two rounds BEFORE you sign a SAFE. Founders are often surprised how much dilution stacks up across notes. A 20-minute spreadsheet exercise saves months of regret.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 108000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (6,1);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (6,2);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (6,3);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (6,4);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (6,6);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (6,7);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (6,8);
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (6,4,'Is there a template you recommend?',((CAST(strftime('%s','now') AS INTEGER)*1000) - 106200000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (6,11,'Yes — see the Learning Hub for a simple dilution model outline.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 105120000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (6,1,'Bookmarked. This is exactly what we are modelling this month.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 104040000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (7,7,'call','Bravo Demo Ventures is reviewing seed and Series A deals in grid technology, battery materials and industrial automation. If you are building hardware with software leverage, we would like to hear from you.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 144000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (7,2);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (7,1);
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (8,4,'update','Delta Startup reached 1,800 teachers on the waitlist this week — all organic, from teacher WhatsApp groups. Now looking for a mentor in marketing and community building.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 172800000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (8,10);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (8,9);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (8,12);
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (8,10,'Community-led growth is a great fit for your audience. Book a slot with me in the Mentor’s Room.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 171000000));
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (8,9,'Congratulations — organic traction like that is a strong signal.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 169920000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (9,9,'learning','Prototype to product-market fit checklist: weekly user interviews, one core metric, a retention curve that flattens, and a paying customer who would be upset if you disappeared. If you cannot tick three of four, keep building.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 198000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (9,1);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (9,2);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (9,3);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (9,4);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (9,6);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (9,10);
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (10,12,'update','Just wrapped a two-day operations workshop with four early-stage teams. The most common gap: no weekly operating rhythm. A simple Monday priorities / Friday review loop changed everything for them.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 252000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (10,1);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (10,3);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (10,7);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (10,8);
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (11,8,'call','Charlie Demo Angels is opening a new syndicate round for early-stage fintech and agri-tech founders. Cheques from $50K. Verified founders welcome to pitch through INverge.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 288000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (11,3);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (11,4);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (11,6);
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (12,1,'update','Milestone: Alpha Startup crossed 40,000 patient visits assisted. A nurse in a clinic with no internet told us the offline mode saved her an hour a day. That is why we build.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 360000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (12,6);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (12,10);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (12,11);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (12,12);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (12,2);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (12,3);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (12,4);
INSERT INTO comments (post_id,user_id,body,created_at) VALUES (12,9,'Offline-first is genuinely hard. Well done to the whole team.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 358200000));
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (13,5,'learning','What I look for in a first meeting: a founder who can explain the problem in one sentence, name three real customers, and tell me what they would do with the money in 18 months.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 432000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (13,1);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (13,2);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (13,3);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (13,4);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (13,10);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (13,11);
INSERT INTO posts (id,user_id,type,body,created_at) VALUES (14,10,'learning','New in the Learning Hub: a guide to your first 100 customers. Spoiler — it is mostly conversations, not campaigns.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 504000000));
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (14,1);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (14,4);
INSERT OR IGNORE INTO post_reactions (post_id,user_id) VALUES (14,2);
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (1,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + 118800)*1000),30,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (2,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + 212400)*1000),45,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (3,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + 306000)*1000),60,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (4,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + 486000)*1000),30,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (5,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + 579600)*1000),45,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (6,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + 759600)*1000),60,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (7,10,((CAST(strftime('%s','now','start of day') AS INTEGER) + 212400)*1000),30,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (8,10,((CAST(strftime('%s','now','start of day') AS INTEGER) + 306000)*1000),45,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (9,10,((CAST(strftime('%s','now','start of day') AS INTEGER) + 399600)*1000),60,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (10,10,((CAST(strftime('%s','now','start of day') AS INTEGER) + 579600)*1000),30,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (11,10,((CAST(strftime('%s','now','start of day') AS INTEGER) + 673200)*1000),45,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (12,10,((CAST(strftime('%s','now','start of day') AS INTEGER) + 810000)*1000),60,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (13,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + 133200)*1000),30,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (14,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + 226800)*1000),45,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (15,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + 320400)*1000),60,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (16,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + 500400)*1000),30,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (17,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + 550800)*1000),45,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (18,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + 730800)*1000),60,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (19,12,((CAST(strftime('%s','now','start of day') AS INTEGER) + 226800)*1000),30,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (20,12,((CAST(strftime('%s','now','start of day') AS INTEGER) + 320400)*1000),45,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (21,12,((CAST(strftime('%s','now','start of day') AS INTEGER) + 414000)*1000),60,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (22,12,((CAST(strftime('%s','now','start of day') AS INTEGER) + 550800)*1000),30,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (23,12,((CAST(strftime('%s','now','start of day') AS INTEGER) + 644400)*1000),45,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (24,12,((CAST(strftime('%s','now','start of day') AS INTEGER) + 824400)*1000),60,'open');
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (25,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + -223200)*1000),30,'booked');
INSERT INTO bookings (id,slot_id,mentor_id,mentee_id,topic,status,created_at) VALUES (1,25,9,1,'Early-stage strategy session','completed',((CAST(strftime('%s','now') AS INTEGER)*1000) - 432000000));
INSERT INTO reviews (booking_id,mentor_id,reviewer_id,rating,body,created_at) VALUES (1,9,1,5,'Great session — clear, honest advice on our seed narrative.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 259200000));
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (26,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + -396000)*1000),30,'booked');
INSERT INTO bookings (id,slot_id,mentor_id,mentee_id,topic,status,created_at) VALUES (2,26,9,2,'Early-stage strategy session','completed',((CAST(strftime('%s','now') AS INTEGER)*1000) - 604800000));
INSERT INTO reviews (booking_id,mentor_id,reviewer_id,rating,body,created_at) VALUES (2,9,2,5,'Helped me think through hardware vs software roadmap.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 432000000));
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (27,9,((CAST(strftime('%s','now','start of day') AS INTEGER) + -568800)*1000),30,'booked');
INSERT INTO bookings (id,slot_id,mentor_id,mentee_id,topic,status,created_at) VALUES (3,27,9,4,'Early-stage strategy session','completed',((CAST(strftime('%s','now') AS INTEGER)*1000) - 777600000));
INSERT INTO reviews (booking_id,mentor_id,reviewer_id,rating,body,created_at) VALUES (3,9,4,4,'Very practical. Would book again.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 604800000));
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (28,10,((CAST(strftime('%s','now','start of day') AS INTEGER) + -741600)*1000),30,'booked');
INSERT INTO bookings (id,slot_id,mentor_id,mentee_id,topic,status,created_at) VALUES (4,28,10,4,'Early-stage strategy session','completed',((CAST(strftime('%s','now') AS INTEGER)*1000) - 950400000));
INSERT INTO reviews (booking_id,mentor_id,reviewer_id,rating,body,created_at) VALUES (4,10,4,5,'Gave me a concrete plan for our first 100 customers.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 777600000));
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (29,10,((CAST(strftime('%s','now','start of day') AS INTEGER) + -914400)*1000),30,'booked');
INSERT INTO bookings (id,slot_id,mentor_id,mentee_id,topic,status,created_at) VALUES (5,29,10,1,'Early-stage strategy session','completed',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1123200000));
INSERT INTO reviews (booking_id,mentor_id,reviewer_id,rating,body,created_at) VALUES (5,10,1,4,'Sharp positioning feedback.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 950400000));
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (30,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + -1087200)*1000),30,'booked');
INSERT INTO bookings (id,slot_id,mentor_id,mentee_id,topic,status,created_at) VALUES (6,30,11,3,'Early-stage strategy session','completed',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1296000000));
INSERT INTO reviews (booking_id,mentor_id,reviewer_id,rating,body,created_at) VALUES (6,11,3,5,'Fixed our financial model in 45 minutes.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1123200000));
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (31,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + -1260000)*1000),30,'booked');
INSERT INTO bookings (id,slot_id,mentor_id,mentee_id,topic,status,created_at) VALUES (7,31,11,1,'Early-stage strategy session','completed',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1468800000));
INSERT INTO reviews (booking_id,mentor_id,reviewer_id,rating,body,created_at) VALUES (7,11,1,5,'Walked through our cap table scenarios clearly.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1296000000));
INSERT INTO mentor_slots (id,mentor_id,starts_at,duration_min,status) VALUES (32,11,((CAST(strftime('%s','now','start of day') AS INTEGER) + -1432800)*1000),30,'booked');
INSERT INTO bookings (id,slot_id,mentor_id,mentee_id,topic,status,created_at) VALUES (8,32,11,2,'Early-stage strategy session','completed',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1641600000));
INSERT INTO reviews (booking_id,mentor_id,reviewer_id,rating,body,created_at) VALUES (8,11,2,5,'Exactly the fundraising prep we needed.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 1468800000));
INSERT INTO questions (id,user_id,title,body,tag,created_at) VALUES (1,4,'How do I find my first 100 users with almost no budget?','We are a pre-seed edtech tool for teachers. Paid ads feel wasteful. What has worked for you?','Marketing',((CAST(strftime('%s','now') AS INTEGER)*1000) - 108000000));
INSERT INTO answers (question_id,user_id,body,created_at) VALUES (1,10,'Go where your users already talk. For teachers that is WhatsApp and Telegram groups, local teacher communities and school WhatsApp parents groups. Offer to build one free resource for the group, then ask for feedback — not signups. Track which conversations turn into repeat usage and double down on that channel only.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 100800000));
INSERT INTO answers (question_id,user_id,body,created_at) VALUES (1,9,'Also record every user interview. Your first 100 users are your best source of product insight, not just distribution.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 97200000));
INSERT INTO questions (id,user_id,title,body,tag,created_at) VALUES (2,2,'When is the right time to start talking to seed investors?','We have 3 pilots and no revenue yet. Are we too early?','Fundraising',((CAST(strftime('%s','now') AS INTEGER)*1000) - 187200000));
INSERT INTO answers (question_id,user_id,body,created_at) VALUES (2,11,'Start relationships 3–6 months before you need the money. Share short updates monthly. Formally raise when you can show a repeatable pattern: pilots converting to paid contracts is that pattern for hardware. Pilots alone, without a path to revenue, usually read as pre-seed.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 180000000));
INSERT INTO questions (id,user_id,title,body,tag,created_at) VALUES (3,3,'How should we think about SAFE vs priced round at seed?','We are raising $2M. Investors are split on instruments.','Finance',((CAST(strftime('%s','now') AS INTEGER)*1000) - 324000000));
INSERT INTO answers (question_id,user_id,body,created_at) VALUES (3,11,'SAFEs are faster and cheaper, but they defer the valuation conversation and can stack dilution. A priced round gives clarity and governance but costs more in legal time. Above ~$1.5M many institutional investors prefer priced. Model both scenarios on your cap table and talk to a startup lawyer before choosing.',((CAST(strftime('%s','now') AS INTEGER)*1000) - 316800000));
INSERT INTO questions (id,user_id,title,body,tag,created_at) VALUES (4,1,'How do you structure the first technical hires after seed?','We are a team of 4 and plan to hire 6 over 12 months.','Talent / HR',((CAST(strftime('%s','now') AS INTEGER)*1000) - 396000000));
INSERT INTO resources (type,title,summary,body,url,author_id,author_name,tags,created_at) VALUES ('guide','The 10-slide pitch deck, explained','What each slide must answer, in the order investors expect.','## The goal
A pitch deck is not your whole story. It earns the first meeting. Aim for 10 slides and under 10 minutes.

## The ten slides
- Problem: who hurts, how often, and what it costs them today.
- Solution: what you built, in one sentence and one screenshot.
- Why now: the shift that makes this possible this year.
- Market: a bottom-up estimate (customers × price), not a top-down percentage.
- Product: three core features tied to the problem.
- Traction: the two or three numbers that prove momentum.
- Business model: how you make money and your unit economics so far.
- Competition: honest alternatives, including "do nothing".
- Team: why you are the people to solve this.
- The ask: how much, what it funds, and the milestone it reaches.

## Common mistakes
- Hiding the ask on the last slide.
- Vanity metrics instead of retention or revenue.
- More than 30 words on a slide.',NULL,NULL,'Founder guide','Fundraising',((CAST(strftime('%s','now') AS INTEGER)*1000) - 2592000000));
INSERT INTO resources (type,title,summary,body,url,author_id,author_name,tags,created_at) VALUES ('template','Founder one-pager template','A single page you can send before any intro call.','## Header
Company name · one-line description · website · founder names and contacts.

## Problem and solution
Two sentences each. Name the customer in the first sentence.

## Traction
- Users or customers: 
- Revenue or pilots: 
- Growth rate (monthly): 

## Market and model
Who pays, how much, and how often.

## Team
Two lines per founder: past relevant wins.

## The ask
Amount, instrument, use of funds, and the 18-month milestone.',NULL,NULL,'Template','Strategy',((CAST(strftime('%s','now') AS INTEGER)*1000) - 2505600000));
INSERT INTO resources (type,title,summary,body,url,author_id,author_name,tags,created_at) VALUES ('template','Monthly investor update email','Keep investors close with a five-minute monthly update.','## Subject line
[Company] — [Month] update: [headline metric]

## Body structure
- Headline: one sentence on the most important change this month.
- Metrics: three numbers vs last month.
- Wins: up to three.
- Challenges: up to three, honestly stated.
- Asks: specific help you want (intros, hires, advice).
- Cash and runway: balance and months of runway.

## Tips
Send on the same day every month. Short beats long. Asks drive replies.',NULL,NULL,'Template','Fundraising',((CAST(strftime('%s','now') AS INTEGER)*1000) - 2419200000));
INSERT INTO resources (type,title,summary,body,url,author_id,author_name,tags,created_at) VALUES ('guide','How investors read a deck in three minutes','Understand the skim so your deck survives it.','## The first pass
Most investors scan for: team credibility, a real problem, evidence of pull from customers, and a reason this is big enough to matter.

## What gets a second look
- A sharp one-line description on the first slide.
- Traction shown as a chart with dates.
- A clear, realistic use of funds.

## What gets a pass
- Vague markets and "no competition" claims.
- Unclear ask or no stated milestone.

Treat the deck as the ticket to a conversation, not the conversation itself.',NULL,NULL,'Investor view','Fundraising',((CAST(strftime('%s','now') AS INTEGER)*1000) - 2332800000));
INSERT INTO resources (type,title,summary,body,url,author_id,author_name,tags,created_at) VALUES ('guide','Preparing for your first mentor session','Walk in with a question, leave with a next step.','## Before
- Write your single most important question.
- Share two lines of context with the mentor in advance.
- Bring one metric that shows where you are today.

## During
Ask for opinions you can test, not instructions. Take notes on commitments.

## After
Within 24 hours, send a short summary of what you will try and when you will report back. Mentors remember founders who follow up.',NULL,NULL,'Mentoring','Strategy',((CAST(strftime('%s','now') AS INTEGER)*1000) - 2246400000));
INSERT INTO resources (type,title,summary,body,url,author_id,author_name,tags,created_at) VALUES ('guide','A plain-language guide to term sheet basics','The handful of terms that shape your outcome. Not legal advice.','## Why it matters
A term sheet sets valuation and the rules of your relationship with investors. Read it with a startup lawyer.

## Terms worth understanding
- Valuation and option pool: pre-money value and how much equity is reserved for hires.
- Liquidation preference: who gets paid first on an exit, and how much.
- Board composition: who controls major decisions.
- Pro-rata rights: investors'' right to participate in future rounds.
- Vesting: founder equity earned over time.

This guide is educational and is not legal advice.',NULL,NULL,'Founder guide','Legal',((CAST(strftime('%s','now') AS INTEGER)*1000) - 2160000000));
INSERT INTO resources (type,title,summary,body,url,author_id,author_name,tags,created_at) VALUES ('video','Sample video resource','Placeholder entry for a learning video (demo content).','','https://example.com/',NULL,'INverge Team','Strategy',((CAST(strftime('%s','now') AS INTEGER)*1000) - 2073600000));
INSERT INTO resources (type,title,summary,body,url,author_id,author_name,tags,created_at) VALUES ('community','Dilution model outline for a SAFE round','A simple spreadsheet outline to model how SAFEs convert at your priced round.','Columns: investor, amount, valuation cap, discount, conversion price, shares issued. Add rows per SAFE, then model the priced round to see post-money ownership for founders, pool and investors. Re-run with 2–3 scenarios before you sign anything.',NULL,11,'Charlie Mentor','Finance,Fundraising',((CAST(strftime('%s','now') AS INTEGER)*1000) - 216000000));
INSERT INTO messages (sender_id,recipient_id,kind,body,meta,created_at,read_at) VALUES (5,1,'pitch','Hi Alpha Founder — Alpha Investor from Alpha Demo Fund. Your Alpha Startup update caught my eye. Could you share more on clinic retention and your offline sync approach?',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 108000000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 104400000));
INSERT INTO messages (sender_id,recipient_id,kind,body,meta,created_at,read_at) VALUES (1,5,'text','Thanks Alpha Investor! Retention is 91% at 90 days across the 12 live clinics. Happy to walk you through the sync design on a call.',NULL,((CAST(strftime('%s','now') AS INTEGER)*1000) - 100800000),((CAST(strftime('%s','now') AS INTEGER)*1000) - 97200000));
INSERT INTO messages (sender_id,recipient_id,kind,body,meta,created_at,read_at) VALUES (5,1,'meeting','Would Thursday work for a 30-minute call?','{"when":1791393444026,"duration":30}',((CAST(strftime('%s','now') AS INTEGER)*1000) - 14400000),NULL);
